# Generated by Django 5.1.4 on 2025-04-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file_path',
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='modules/'),
        ),
    ]
